---
- shell: uname -s
  register: uname_s

- shell: uname -m
  register: uname_m

- set_fact:
      docker_compose_url: "https://github.com/docker/compose/releases/download/1.6.2/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout}}"

- name: Install docker compose
  get_url: url={{ docker_compose_url }} dest=/usr/local/bin/docker-compose

- name: Apply executable permissions do docker compose
  file: path=/usr/local/bin/docker-compose mode=755