---
- name: apt-get update
  apt: update_cache=yes
  
- name: Update package information, ensure that APT works with the https method, and that CA certificates are installed.
  apt: name={{ item }}
  with_items:
   - apt-transport-https 
   - ca-certificates

- name: Add the new GPG key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Add an entry for your Ubuntu operating system
  shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list

- name: apt-get update
  apt: update_cache=yes

- name: Verify that APT is pulling from the right repository
  shell: apt-cache policy docker-engine  

- shell: uname -r
  register: uname

- set_fact:
      extra_image_cmd: "linux-image-extra-{{ uname.stdout }}"

- name: Install the {{ extra_image_cmd }} kernel package
  apt: name={{ extra_image_cmd }} force=yes

- name: On Ubuntu 14.04 apparmor is required
  apt: name=apparmor

- name: apt-get update
  apt: update_cache=yes

- name: Install Docker
  apt: name=docker-engine

- name: Create the docker group and add vagrant user
  shell: usermod -aG docker vagrant